version: '3.9'

services:
  mongoDocXas:
    image: mongo
    container_name: mongoDocXas
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

    ports:
      - 27018:27017
    networks:
      - docxas

  documentator:
    environment:
      MONGODB_URI: mongodb://root:example@mongoDocXas:27017/
    build: ./services/documentator/.
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongoDocXas
    networks:
      - docxas

networks:
  docxas:
    driver: bridge
